"""
Financial Plan PDF Generator - Creates professional PDF financial plans
Supports: full profile plans, topic-specific plans (car, house, etc.), guest plans
"""

from typing import Dict, Any, Optional
from langchain.tools import tool
from datetime import datetime
import os
import json
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT

# ── Output directory ──────────────────────────────────────────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
PLANS_DIR = os.path.join(_HERE, "..", "allPlans")


def ensure_plans_directory() -> str:
    os.makedirs(PLANS_DIR, exist_ok=True)
    return PLANS_DIR


def format_currency(amount) -> str:
    try:
        v = float(amount)
        return f"${v:,.2f}" if v >= 0 else f"-${abs(v):,.2f}"
    except (ValueError, TypeError):
        return str(amount)


def _render_goals(story, goals_raw, normal_style):
    """Render goals from dict, list, or plain string."""
    if isinstance(goals_raw, str):
        try:
            goals_raw = json.loads(goals_raw)
        except Exception:
            story.append(Paragraph(f"• {goals_raw}", normal_style))
            return
    if isinstance(goals_raw, dict):
        for key, value in goals_raw.items():
            label = key.replace("_", " ").title()
            story.append(Paragraph(f"• <b>{label}:</b> {value}", normal_style))
    elif isinstance(goals_raw, list):
        for item in goals_raw:
            story.append(Paragraph(f"• {item}", normal_style))
    else:
        story.append(Paragraph(f"• {goals_raw}", normal_style))


def _make_styles() -> Dict:
    """Return a dict of all reusable paragraph styles."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("CTitle", parent=base["Title"], fontSize=26,
                                spaceAfter=14, textColor=colors.HexColor("#1a4d8c"),
                                alignment=TA_CENTER, fontName="Helvetica-Bold"),
        "subtitle": ParagraphStyle("CSub", parent=base["Normal"], fontSize=12,
                                   alignment=TA_CENTER, spaceAfter=6,
                                   textColor=colors.HexColor("#7f8c8d")),
        "info_bar": ParagraphStyle("CBar", parent=base["Normal"], fontSize=9,
                                   alignment=TA_CENTER, textColor=colors.white,
                                   backColor=colors.HexColor("#3498db"),
                                   borderPadding=(6, 10, 6, 10)),
        "heading": ParagraphStyle("CHead", parent=base["Heading2"], fontSize=14,
                                  spaceBefore=14, spaceAfter=7,
                                  textColor=colors.HexColor("#2c3e50"),
                                  fontName="Helvetica-Bold"),
        "subheading": ParagraphStyle("CSubHead", parent=base["Heading3"], fontSize=12,
                                     spaceBefore=8, spaceAfter=5,
                                     textColor=colors.HexColor("#34495e"),
                                     fontName="Helvetica-Bold"),
        "normal": ParagraphStyle("CNorm", parent=base["Normal"], fontSize=10,
                                 spaceAfter=6, leading=14,
                                 textColor=colors.HexColor("#2c3e50"),
                                 fontName="Helvetica"),
        "small": ParagraphStyle("CSmall", parent=base["Normal"], fontSize=8,
                                spaceAfter=4, leading=10,
                                textColor=colors.HexColor("#7f8c8d"),
                                fontName="Helvetica-Oblique"),
        "footer": ParagraphStyle("CFoot", parent=base["Normal"], fontSize=7,
                                 alignment=TA_CENTER,
                                 textColor=colors.HexColor("#95a5a6")),
    }


def _header(story, plan_name: str, user_label: str, S: Dict):
    story.append(Paragraph("CoFina", S["title"]))
    story.append(Paragraph("Intelligent Financial Planning for Young Professionals", S["subtitle"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(
        f"Plan: {plan_name}  |  Generated: {datetime.now().strftime('%B %d, %Y')}  |  For: {user_label}",
        S["info_bar"]
    ))
    story.append(Spacer(1, 0.2 * inch))


def _footer(story, timestamp: str, S: Dict):
    story.append(Spacer(1, 0.25 * inch))
    story.append(Paragraph(
        f"Generated by CoFina AI  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  Plan ID: {timestamp}",
        S["footer"]
    ))


def _budget_table(story, income, S: Dict):
    """50/30/20 table from annual income."""
    monthly = float(income) / 12
    rows = [
        ["Category", "Allocation", "Monthly", "Annual"],
        ["Needs (Essentials)", "50%", format_currency(monthly * .5), format_currency(float(income) * .5)],
        ["Wants (Lifestyle)",  "30%", format_currency(monthly * .3), format_currency(float(income) * .3)],
        ["Savings & Debt",     "20%", format_currency(monthly * .2), format_currency(float(income) * .2)],
        ["Total",             "100%", format_currency(monthly),       format_currency(float(income))],
    ]
    t = Table(rows, colWidths=[1.8*inch, 0.8*inch, 1.3*inch, 1.4*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND",     (0, 0), (-1, 0),  colors.HexColor("#3498db")),
        ("TEXTCOLOR",      (0, 0), (-1, 0),  colors.whitesmoke),
        ("FONTNAME",       (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0), (-1, 0),  10),
        ("BOTTOMPADDING",  (0, 0), (-1, 0),  10),
        ("TOPPADDING",     (0, 0), (-1, 0),  10),
        ("ALIGN",          (0, 0), (-1, -1), "CENTER"),
        ("GRID",           (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("FONTNAME",       (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",       (0, 1), (-1, -1), 9),
        ("BACKGROUND",     (0, 4), (-1, 4),  colors.HexColor("#ecf0f1")),
        ("FONTNAME",       (0, 4), (-1, 4),  "Helvetica-Bold"),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.1 * inch))


# ═════════════════════════════════════════════════════════════════════════════
# FULL PROFILE PLAN
# ═════════════════════════════════════════════════════════════════════════════

def create_financial_plan_pdf(
    user_id: str,
    profile_data,
    short_term_goals,
    long_term_goals,
    plan_name: str = "Financial Plan",
    include_projections: bool = True,
) -> Dict[str, Any]:
    """Full personalised financial plan PDF (profile-based)."""
    try:
        plans_dir = ensure_plans_directory()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe = "".join(c for c in user_id if c.isalnum() or c in "._-")
        filename = f"{safe}_{plan_name.replace(' ', '_')}_{timestamp}.pdf"
        filepath = os.path.join(plans_dir, filename)

        doc = SimpleDocTemplate(filepath, pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch,
                                leftMargin=0.75*inch, rightMargin=0.75*inch,
                                title=f"CoFina – {plan_name} – {user_id}",
                                author="CoFina AI")
        S = _make_styles()
        story = []

        # Parse profile
        if isinstance(profile_data, str):
            try:
                profile_data = json.loads(profile_data)
            except Exception:
                profile_data = {}
        profile_data = profile_data or {}
        profile_sub = profile_data.get("profile", {}) or {}
        preferences  = profile_data.get("preferences", {}) or {}
        income       = profile_data.get("income")
        name = (f"{profile_data.get('first_name','')} {profile_data.get('other_names','')}").strip() or user_id

        _header(story, plan_name, name, S)

        # Executive Summary
        story.append(Paragraph("Executive Summary", S["heading"]))
        age       = profile_sub.get("age", "")
        profession = profile_sub.get("profession", "")
        parts = [f"This personalised plan was created for <b>{name}</b>"]
        if age:       parts.append(f", aged {age}")
        if profession: parts.append(f", working as a <b>{profession}</b>")
        parts.append(
            ". It is designed to guide you toward financial independence through disciplined "
            "budgeting, strategic debt management, and goal-oriented saving and investing."
        )
        story.append(Paragraph("".join(parts), S["normal"]))
        story.append(Spacer(1, 0.1 * inch))

        # Profile table
        story.append(Paragraph("Your Financial Profile", S["heading"]))
        rows = []
        if income:
            rows += [["Annual Income",  format_currency(income)],
                     ["Monthly Income", format_currency(float(income) / 12)]]
        if age:        rows.append(["Age", str(age)])
        if profession: rows.append(["Profession", profession])
        ret_age = profile_sub.get("retirement_age")
        if ret_age:    rows.append(["Target Retirement Age", str(ret_age)])
        risk_map = {"low": "Conservative", "moderate": "Moderate", "high": "Aggressive"}
        risk = preferences.get("risk_profile", "").lower()
        if risk:       rows.append(["Risk Tolerance", risk_map.get(risk, risk.title())])
        if preferences.get("debt_strategy"):
            rows.append(["Debt Strategy", preferences["debt_strategy"].title()])
        if preferences.get("savings_priority"):
            rows.append(["Savings Priority", preferences["savings_priority"].replace("_", " ").title()])

        if rows:
            t = Table(rows, colWidths=[2.2*inch, 3.3*inch])
            t.setStyle(TableStyle([
                ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME",       (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE",       (0, 0), (-1, -1), 10),
                ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING",  (0, 0), (-1, -1), 7),
                ("TOPPADDING",     (0, 0), (-1, -1), 7),
                ("GRID",           (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1),
                 [colors.HexColor("#f8f9fa"), colors.white]),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.12 * inch))

        # Debts
        debts = profile_data.get("debts", [])
        if debts:
            story.append(Paragraph("Current Debts", S["heading"]))
            drows = [["Debt", "Total", "Remaining", "Rate", "Min. Payment"]]
            for d in debts:
                drows.append([
                    d.get("name", "—"),
                    format_currency(d.get("total_amount", 0)),
                    format_currency(d.get("remaining_amount", 0)),
                    f"{d.get('interest_rate', 0)}%",
                    format_currency(d.get("minimum_payment", 0)) + "/mo",
                ])
            dt = Table(drows, colWidths=[1.5*inch, 1.1*inch, 1.1*inch, 0.7*inch, 1.2*inch])
            dt.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, 0), colors.HexColor("#e74c3c")),
                ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
                ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",      (0, 0), (-1, 0), 9),
                ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
                ("GRID",          (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE",      (0, 1), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ]))
            story.append(dt)
            strat = preferences.get("debt_strategy", "avalanche").lower()
            tip = ("Snowball: Clear smallest balances first for momentum."
                   if strat == "snowball"
                   else "Avalanche: Attack highest-interest debt first to minimise total interest paid.")
            story.append(Spacer(1, 4))
            story.append(Paragraph(f"💡 Your strategy: {tip}", S["small"]))
            story.append(Spacer(1, 0.12 * inch))

        # Goals
        story.append(Paragraph("Financial Goals", S["heading"]))
        story.append(Paragraph("Short-term (1–2 years)", S["subheading"]))
        _render_goals(story, short_term_goals, S["normal"])
        story.append(Spacer(1, 0.06 * inch))
        story.append(Paragraph("Long-term (5+ years)", S["subheading"]))
        _render_goals(story, long_term_goals, S["normal"])
        story.append(Spacer(1, 0.12 * inch))

        # Budget
        if income:
            story.append(Paragraph("Recommended Monthly Budget (50/30/20 Rule)", S["heading"]))
            _budget_table(story, income, S)

        # Action plan
        story.append(Paragraph("Your Action Plan", S["heading"]))
        for a in [
            "1. <b>Build Emergency Fund</b> — 3–6 months of expenses before investing.",
            "2. <b>Automate savings</b> — set up automatic transfers on payday.",
            "3. <b>Attack debt</b> — follow your chosen repayment strategy consistently.",
            "4. <b>Review monthly</b> — track spending and adjust budget categories.",
            "5. <b>Maximise retirement contributions</b> — capture any employer match first.",
            "6. <b>Invest the surplus</b> — low-cost index funds for long-term wealth.",
            "7. <b>Annual review</b> — update this plan every year or after major life events.",
        ]:
            story.append(Paragraph(a, S["normal"]))
        story.append(Spacer(1, 0.12 * inch))

        # Projections
        if include_projections and income:
            story.append(Paragraph("Savings Projections (20% rate, 5% annual return)", S["heading"]))
            annual_sav = float(income) * 0.20
            prows = [["Horizon", "Projected Savings", "Monthly Contribution"]]
            for y in [1, 3, 5, 10, 20]:
                fv = annual_sav * ((1.05**y - 1) / 0.05)
                prows.append([f"{y} yr{'s' if y > 1 else ''}", format_currency(fv),
                              format_currency(annual_sav / 12)])
            pt = Table(prows, colWidths=[1.2*inch, 2.0*inch, 2.0*inch])
            pt.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, 0), colors.HexColor("#27ae60")),
                ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
                ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",      (0, 0), (-1, 0), 10),
                ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
                ("GRID",          (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE",      (0, 1), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ]))
            story.append(pt)
            story.append(Spacer(1, 4))
            story.append(Paragraph("* Projections are estimates. Actual returns will vary.", S["small"]))
            story.append(Spacer(1, 0.12 * inch))

        # Disclaimer
        story.append(Paragraph("Disclosures", S["heading"]))
        story.append(Paragraph(
            "This plan is for informational purposes only and does not constitute financial, "
            "investment, or tax advice. CoFina is an AI assistant, not a licensed financial adviser. "
            "Please consult a qualified professional before making major financial decisions.",
            S["small"]
        ))
        _footer(story, timestamp, S)
        doc.build(story)

        return {"success": True, "filepath": filepath, "filename": filename,
                "user_id": user_id, "generated_at": datetime.now().isoformat(),
                "message": f"PDF saved to: {filepath}"}

    except Exception as e:
        return {"success": False, "error": str(e), "user_id": user_id,
                "message": f"PDF generation failed: {str(e)}"}


# ═════════════════════════════════════════════════════════════════════════════
# TOPIC-SPECIFIC PLAN  (car, house, debt payoff, etc.)
# ═════════════════════════════════════════════════════════════════════════════

def create_topic_plan_pdf(
    user_id: str,
    topic: str,
    plan_content: str,
    profile_data: Optional[Dict] = None,
    plan_name: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate a PDF for any topic-specific plan already written by the agent.
    `plan_content` is the full text; `profile_data` personalises the header.
    """
    try:
        plans_dir = ensure_plans_directory()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe = "".join(c for c in user_id if c.isalnum() or c in "._-")
        plan_label = plan_name or f"{topic.title()} Plan"
        filename = f"{safe}_{topic.replace(' ', '_')}_plan_{timestamp}.pdf"
        filepath = os.path.join(plans_dir, filename)

        doc = SimpleDocTemplate(filepath, pagesize=letter,
                                topMargin=0.75*inch, bottomMargin=0.75*inch,
                                leftMargin=0.75*inch, rightMargin=0.75*inch,
                                title=f"CoFina – {plan_label} – {user_id}",
                                author="CoFina AI")
        S = _make_styles()
        story = []

        profile_data = profile_data or {}
        income = profile_data.get("income")
        name = (f"{profile_data.get('first_name','')} "
                f"{profile_data.get('other_names','')}").strip() or user_id

        _header(story, plan_label, name, S)

        # Personal context sidebar
        profile_sub = profile_data.get("profile", {}) or {}
        ctx_rows = []
        if name and name != user_id:
            ctx_rows.append(["Name", name])
        prof = profile_sub.get("profession", "")
        if prof:    ctx_rows.append(["Profession", prof])
        if income:
            ctx_rows.append(["Monthly Income", format_currency(float(income) / 12)])
            ctx_rows.append(["Annual Income",  format_currency(income)])
        if ctx_rows:
            story.append(Paragraph("Your Profile Snapshot", S["heading"]))
            ct = Table(ctx_rows, colWidths=[2.0*inch, 3.5*inch])
            ct.setStyle(TableStyle([
                ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME",       (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE",       (0, 0), (-1, -1), 10),
                ("GRID",           (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("BOTTOMPADDING",  (0, 0), (-1, -1), 6),
                ("TOPPADDING",     (0, 0), (-1, -1), 6),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1),
                 [colors.HexColor("#f8f9fa"), colors.white]),
            ]))
            story.append(ct)
            story.append(Spacer(1, 0.12 * inch))

        # Main plan body
        story.append(Paragraph(f"Your {plan_label}", S["heading"]))
        for line in plan_content.splitlines():
            line = line.strip()
            if not line:
                story.append(Spacer(1, 5))
                continue
            clean = line.replace("**", "")
            if line.startswith("**") and line.endswith("**"):
                story.append(Paragraph(clean, S["subheading"]))
            elif line.startswith("##"):
                story.append(Paragraph(line.replace("##", "").strip(), S["subheading"]))
            elif line[0].isdigit() and len(line) > 1 and line[1] in ".)" :
                story.append(Paragraph(line, S["normal"]))
            elif line.startswith(("*", "-", "•")):
                story.append(Paragraph("• " + line.lstrip("*-• "), S["normal"]))
            else:
                story.append(Paragraph(line, S["normal"]))
        story.append(Spacer(1, 0.12 * inch))

        # Budget reference
        if income:
            story.append(Paragraph("Budget Reference (50/30/20)", S["heading"]))
            _budget_table(story, income, S)

        # Disclaimer
        story.append(Paragraph("Disclosures", S["heading"]))
        story.append(Paragraph(
            "This plan is for informational purposes only and does not constitute financial, "
            "investment, or tax advice. CoFina is an AI assistant, not a licensed financial adviser.",
            S["small"]
        ))
        _footer(story, timestamp, S)
        doc.build(story)

        return {"success": True, "filepath": filepath, "filename": filename,
                "user_id": user_id, "generated_at": datetime.now().isoformat(),
                "message": f"PDF saved to: {filepath}"}

    except Exception as e:
        return {"success": False, "error": str(e), "user_id": user_id,
                "message": f"PDF generation failed: {str(e)}"}


# ── LangChain tool wrapper ─────────────────────────────────────────────────────

@tool
def generate_financial_plan_pdf(
    user_id: str,
    profile_data: str,
    short_term_goals: str,
    long_term_goals: str,
    plan_name: str = "Financial Plan",
    include_projections: bool = True,
) -> Dict[str, Any]:
    """Generate a full personalised financial plan PDF from a user profile."""
    return create_financial_plan_pdf(
        user_id=user_id,
        profile_data=profile_data,
        short_term_goals=short_term_goals,
        long_term_goals=long_term_goals,
        plan_name=plan_name,
        include_projections=include_projections,
    )